FROM bmelnik0/app-protect-clean

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 50055

COPY nginx.conf /etc/nginx/nginx.conf
COPY policy.json /etc/nginx/policy.json
COPY custom_log_format.json /etc/nginx/custom_log_format.json
